// Code generated by MockGen. DO NOT EDIT.
// Source: ./vendor/github.com/serverscom/serverscom-go-client/pkg/kubernetes_clusters.go
//
// Generated by this command:
//
//	mockgen --destination ./internal/testing/kubernetes_clusters_mock.go --package=serverscom_testing --source ./vendor/github.com/serverscom/serverscom-go-client/pkg/kubernetes_clusters.go
//

// Package serverscom_testing is a generated GoMock package.
package serverscom_testing

import (
	context "context"
	reflect "reflect"

	serverscom "github.com/serverscom/serverscom-go-client/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockKubernetesClustersService is a mock of KubernetesClustersService interface.
type MockKubernetesClustersService struct {
	ctrl     *gomock.Controller
	recorder *MockKubernetesClustersServiceMockRecorder
	isgomock struct{}
}

// MockKubernetesClustersServiceMockRecorder is the mock recorder for MockKubernetesClustersService.
type MockKubernetesClustersServiceMockRecorder struct {
	mock *MockKubernetesClustersService
}

// NewMockKubernetesClustersService creates a new mock instance.
func NewMockKubernetesClustersService(ctrl *gomock.Controller) *MockKubernetesClustersService {
	mock := &MockKubernetesClustersService{ctrl: ctrl}
	mock.recorder = &MockKubernetesClustersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubernetesClustersService) EXPECT() *MockKubernetesClustersServiceMockRecorder {
	return m.recorder
}

// AutoscaleNodeGroupNodes mocks base method.
func (m *MockKubernetesClustersService) AutoscaleNodeGroupNodes(clusterID, nodeGroupID string) serverscom.Collection[serverscom.KubernetesClusterNode] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoscaleNodeGroupNodes", clusterID, nodeGroupID)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.KubernetesClusterNode])
	return ret0
}

// AutoscaleNodeGroupNodes indicates an expected call of AutoscaleNodeGroupNodes.
func (mr *MockKubernetesClustersServiceMockRecorder) AutoscaleNodeGroupNodes(clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoscaleNodeGroupNodes", reflect.TypeOf((*MockKubernetesClustersService)(nil).AutoscaleNodeGroupNodes), clusterID, nodeGroupID)
}

// AutoscaleNodeGroups mocks base method.
func (m *MockKubernetesClustersService) AutoscaleNodeGroups(clusterID string) serverscom.Collection[serverscom.KubernetesClusterAutoscaleNodeGroup] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoscaleNodeGroups", clusterID)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.KubernetesClusterAutoscaleNodeGroup])
	return ret0
}

// AutoscaleNodeGroups indicates an expected call of AutoscaleNodeGroups.
func (mr *MockKubernetesClustersServiceMockRecorder) AutoscaleNodeGroups(clusterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoscaleNodeGroups", reflect.TypeOf((*MockKubernetesClustersService)(nil).AutoscaleNodeGroups), clusterID)
}

// Collection mocks base method.
func (m *MockKubernetesClustersService) Collection() serverscom.Collection[serverscom.KubernetesCluster] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection")
	ret0, _ := ret[0].(serverscom.Collection[serverscom.KubernetesCluster])
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockKubernetesClustersServiceMockRecorder) Collection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockKubernetesClustersService)(nil).Collection))
}

// CreateAutoscaleNodeGroup mocks base method.
func (m *MockKubernetesClustersService) CreateAutoscaleNodeGroup(ctx context.Context, clusterID string, input serverscom.KubernetesClusterAutoscaleNodeGroupCreateInput) (*serverscom.KubernetesClusterAutoscaleNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutoscaleNodeGroup", ctx, clusterID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAutoscaleNodeGroup indicates an expected call of CreateAutoscaleNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) CreateAutoscaleNodeGroup(ctx, clusterID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutoscaleNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).CreateAutoscaleNodeGroup), ctx, clusterID, input)
}

// CreateNodeGroup mocks base method.
func (m *MockKubernetesClustersService) CreateNodeGroup(ctx context.Context, clusterID string, input serverscom.KubernetesClusterNodeGroupCreateInput) (*serverscom.KubernetesClusterNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeGroup", ctx, clusterID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNodeGroup indicates an expected call of CreateNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) CreateNodeGroup(ctx, clusterID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).CreateNodeGroup), ctx, clusterID, input)
}

// DecreaseAutoscaleNodeGroupTargetSize mocks base method.
func (m *MockKubernetesClustersService) DecreaseAutoscaleNodeGroupTargetSize(ctx context.Context, clusterID, nodeGroupID string, input serverscom.KubernetesClusterAutoscaleNodeGroupDecreaseTargetSizeInput) (*serverscom.KubernetesClusterAutoscaleNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseAutoscaleNodeGroupTargetSize", ctx, clusterID, nodeGroupID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseAutoscaleNodeGroupTargetSize indicates an expected call of DecreaseAutoscaleNodeGroupTargetSize.
func (mr *MockKubernetesClustersServiceMockRecorder) DecreaseAutoscaleNodeGroupTargetSize(ctx, clusterID, nodeGroupID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseAutoscaleNodeGroupTargetSize", reflect.TypeOf((*MockKubernetesClustersService)(nil).DecreaseAutoscaleNodeGroupTargetSize), ctx, clusterID, nodeGroupID, input)
}

// DeleteAutoscaleNodeGroup mocks base method.
func (m *MockKubernetesClustersService) DeleteAutoscaleNodeGroup(ctx context.Context, clusterID, nodeGroupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAutoscaleNodeGroup", ctx, clusterID, nodeGroupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAutoscaleNodeGroup indicates an expected call of DeleteAutoscaleNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) DeleteAutoscaleNodeGroup(ctx, clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAutoscaleNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).DeleteAutoscaleNodeGroup), ctx, clusterID, nodeGroupID)
}

// DeleteAutoscaleNodeGroupNodes mocks base method.
func (m *MockKubernetesClustersService) DeleteAutoscaleNodeGroupNodes(ctx context.Context, clusterID, nodeGroupID string, input serverscom.KubernetesClusterAutoscaleNodeGroupDeleteNodesInput) (*serverscom.KubernetesClusterAutoscaleNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAutoscaleNodeGroupNodes", ctx, clusterID, nodeGroupID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAutoscaleNodeGroupNodes indicates an expected call of DeleteAutoscaleNodeGroupNodes.
func (mr *MockKubernetesClustersServiceMockRecorder) DeleteAutoscaleNodeGroupNodes(ctx, clusterID, nodeGroupID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAutoscaleNodeGroupNodes", reflect.TypeOf((*MockKubernetesClustersService)(nil).DeleteAutoscaleNodeGroupNodes), ctx, clusterID, nodeGroupID, input)
}

// DeleteNodeGroup mocks base method.
func (m *MockKubernetesClustersService) DeleteNodeGroup(ctx context.Context, clusterID, nodeGroupID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeGroup", ctx, clusterID, nodeGroupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeGroup indicates an expected call of DeleteNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) DeleteNodeGroup(ctx, clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).DeleteNodeGroup), ctx, clusterID, nodeGroupID)
}

// Get mocks base method.
func (m *MockKubernetesClustersService) Get(ctx context.Context, id string) (*serverscom.KubernetesCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*serverscom.KubernetesCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKubernetesClustersServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKubernetesClustersService)(nil).Get), ctx, id)
}

// GetAutoscaleNodeGroup mocks base method.
func (m *MockKubernetesClustersService) GetAutoscaleNodeGroup(ctx context.Context, clusterID, nodeGroupID string) (*serverscom.KubernetesClusterAutoscaleNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoscaleNodeGroup", ctx, clusterID, nodeGroupID)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoscaleNodeGroup indicates an expected call of GetAutoscaleNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) GetAutoscaleNodeGroup(ctx, clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoscaleNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).GetAutoscaleNodeGroup), ctx, clusterID, nodeGroupID)
}

// GetAutoscaleNodeGroupTemplate mocks base method.
func (m *MockKubernetesClustersService) GetAutoscaleNodeGroupTemplate(ctx context.Context, clusterID, nodeGroupID string) (*serverscom.KubernetesClusterAutoscaleNodeGroupTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutoscaleNodeGroupTemplate", ctx, clusterID, nodeGroupID)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroupTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutoscaleNodeGroupTemplate indicates an expected call of GetAutoscaleNodeGroupTemplate.
func (mr *MockKubernetesClustersServiceMockRecorder) GetAutoscaleNodeGroupTemplate(ctx, clusterID, nodeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutoscaleNodeGroupTemplate", reflect.TypeOf((*MockKubernetesClustersService)(nil).GetAutoscaleNodeGroupTemplate), ctx, clusterID, nodeGroupID)
}

// GetNode mocks base method.
func (m *MockKubernetesClustersService) GetNode(ctx context.Context, clusterID, nodeID string) (*serverscom.KubernetesClusterNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, clusterID, nodeID)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockKubernetesClustersServiceMockRecorder) GetNode(ctx, clusterID, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockKubernetesClustersService)(nil).GetNode), ctx, clusterID, nodeID)
}

// IncreaseAutoscaleNodeGroupSize mocks base method.
func (m *MockKubernetesClustersService) IncreaseAutoscaleNodeGroupSize(ctx context.Context, clusterID, nodeGroupID string, input serverscom.KubernetesClusterAutoscaleNodeGroupIncreaseSizeInput) (*serverscom.KubernetesClusterAutoscaleNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseAutoscaleNodeGroupSize", ctx, clusterID, nodeGroupID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseAutoscaleNodeGroupSize indicates an expected call of IncreaseAutoscaleNodeGroupSize.
func (mr *MockKubernetesClustersServiceMockRecorder) IncreaseAutoscaleNodeGroupSize(ctx, clusterID, nodeGroupID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseAutoscaleNodeGroupSize", reflect.TypeOf((*MockKubernetesClustersService)(nil).IncreaseAutoscaleNodeGroupSize), ctx, clusterID, nodeGroupID, input)
}

// MoveNodes mocks base method.
func (m *MockKubernetesClustersService) MoveNodes(ctx context.Context, clusterID string, input serverscom.KubernetesClusterMoveNodesInput) ([]serverscom.KubernetesClusterNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveNodes", ctx, clusterID, input)
	ret0, _ := ret[0].([]serverscom.KubernetesClusterNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveNodes indicates an expected call of MoveNodes.
func (mr *MockKubernetesClustersServiceMockRecorder) MoveNodes(ctx, clusterID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveNodes", reflect.TypeOf((*MockKubernetesClustersService)(nil).MoveNodes), ctx, clusterID, input)
}

// NodeGroups mocks base method.
func (m *MockKubernetesClustersService) NodeGroups(id string) serverscom.Collection[serverscom.KubernetesClusterNodeGroup] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeGroups", id)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.KubernetesClusterNodeGroup])
	return ret0
}

// NodeGroups indicates an expected call of NodeGroups.
func (mr *MockKubernetesClustersServiceMockRecorder) NodeGroups(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeGroups", reflect.TypeOf((*MockKubernetesClustersService)(nil).NodeGroups), id)
}

// Nodes mocks base method.
func (m *MockKubernetesClustersService) Nodes(id string) serverscom.Collection[serverscom.KubernetesClusterNode] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nodes", id)
	ret0, _ := ret[0].(serverscom.Collection[serverscom.KubernetesClusterNode])
	return ret0
}

// Nodes indicates an expected call of Nodes.
func (mr *MockKubernetesClustersServiceMockRecorder) Nodes(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nodes", reflect.TypeOf((*MockKubernetesClustersService)(nil).Nodes), id)
}

// Update mocks base method.
func (m *MockKubernetesClustersService) Update(ctx context.Context, id string, input serverscom.KubernetesClusterUpdateInput) (*serverscom.KubernetesCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*serverscom.KubernetesCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockKubernetesClustersServiceMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockKubernetesClustersService)(nil).Update), ctx, id, input)
}

// UpdateAutoscaleNodeGroup mocks base method.
func (m *MockKubernetesClustersService) UpdateAutoscaleNodeGroup(ctx context.Context, clusterID, nodeGroupID string, input serverscom.KubernetesClusterAutoscaleNodeGroupUpdateInput) (*serverscom.KubernetesClusterAutoscaleNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutoscaleNodeGroup", ctx, clusterID, nodeGroupID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterAutoscaleNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAutoscaleNodeGroup indicates an expected call of UpdateAutoscaleNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) UpdateAutoscaleNodeGroup(ctx, clusterID, nodeGroupID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutoscaleNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).UpdateAutoscaleNodeGroup), ctx, clusterID, nodeGroupID, input)
}

// UpdateNode mocks base method.
func (m *MockKubernetesClustersService) UpdateNode(ctx context.Context, clusterID, nodeID string, input serverscom.KubernetesClusterNodeUpdateInput) (*serverscom.KubernetesClusterNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNode", ctx, clusterID, nodeID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNode indicates an expected call of UpdateNode.
func (mr *MockKubernetesClustersServiceMockRecorder) UpdateNode(ctx, clusterID, nodeID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNode", reflect.TypeOf((*MockKubernetesClustersService)(nil).UpdateNode), ctx, clusterID, nodeID, input)
}

// UpdateNodeGroup mocks base method.
func (m *MockKubernetesClustersService) UpdateNodeGroup(ctx context.Context, clusterID, nodeGroupID string, input serverscom.KubernetesClusterNodeGroupUpdateInput) (*serverscom.KubernetesClusterNodeGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeGroup", ctx, clusterID, nodeGroupID, input)
	ret0, _ := ret[0].(*serverscom.KubernetesClusterNodeGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNodeGroup indicates an expected call of UpdateNodeGroup.
func (mr *MockKubernetesClustersServiceMockRecorder) UpdateNodeGroup(ctx, clusterID, nodeGroupID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeGroup", reflect.TypeOf((*MockKubernetesClustersService)(nil).UpdateNodeGroup), ctx, clusterID, nodeGroupID, input)
}
